#!/bin/bash

set -eu

export DEBIAN_FRONTEND=noninteractive
MYSQL_USER_PASSWORD=123456
MYSQL_ROOT_PASSWORD=123456

apt-key adv --keyserver keys.gnupg.net --recv-keys 1C4CBDCDCD2EFD2A
echo "deb http://repo.percona.com/apt "$(lsb_release -sc)" main" | tee /etc/apt/sources.list.d/percona.list

apt-get update

apt-get install -y percona-server-server-5.6 percona-server-client-5.6

cp -f /config/lxc/percona/my.cnf /etc/mysql/
/etc/init.d/mysql restart
